name: Update Links and Deploy

on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        npm install

    - name: Fetch Gametwist Links
      run: |
        node -e "
        const axios = require('axios');
        const cheerio = require('cheerio');
        const fs = require('fs');
        const url = 'https://www.gaminatorbonuscode.net/';

        axios.get(url).then(({ data }) => {
          const $ = cheerio.load(data);
          const links = [];
          $('a[href*=\"gametwist\"]').each((index, element) => {
            links.push($(element).attr('href'));
          });
          console.log('Fetched links:', links);
          fs.writeFileSync('links.json', JSON.stringify(links));
        }).catch(err => {
          console.error('Error fetching links:', err);
          process.exit(1);  // Exit with an error code
        });
        "

    - name: Update Reward Page
      run: |
        echo "<html><body>" > reward.html
        jq -r '.[] | "<a href=\"\(.href)\">Gametwist Free Coins</a><br/>"' links.json >> reward.html
        echo "</body></html>" >> reward.html

    - name: Configure Git
      run: |
        git config --global user.email "prolladmail@gmail.com"
        git config --global user.name "Prollad99"

    - name: Commit changes
      run: |
        git add reward.html
        git commit -m "Update reward links"

     - name: Push changes
        env:
          TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        run: |
          git push https://x-access-token:${{ secrets.ACTIONS_DEPLOY_KEY }}@github.com/Prollad99/Gtwst.git
