name: Update Reward Page

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Update Reward Page
      run: |
        echo "<html><body>" > reward.html
        jq -r '.[] | "<a href=\"\(.href)\">Gametwist Free Coins</a><br/>"' links.json >> reward.html
        echo "</body></html>" >> reward.html
        git config --global user.email "prolladmail@gmail.com"
        git config --global user.name "Prollad99"
        git add reward.html
        git commit -m "Update reward links"
        git push
